# -*- coding: utf-8 -*-
"""sea_level_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ColgJ9LrYs7mh_Pwhj-wu2C0_k-LeT7D
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress
import numpy as np

df = pd.read_csv('/content/epa-sea-level.csv')

plt.figure(figsize=(10,6))
plt.scatter(df['Year'], df['CSIRO Adjusted Sea Level'])

res_all = linregress(df['Year'], df['CSIRO Adjusted Sea Level'])

years_extended = np.arange(df['Year'].min(), 2051)
sea_level_all = res_all.intercept + res_all.slope * years_extended

plt.plot(years_extended, sea_level_all, color='red')

df_2000 = df[df['Year'] >= 2000]

res_2000 = linregress(df_2000['Year'], df_2000['CSIRO Adjusted Sea Level'])

years_2000_extended = np.arange(2000, 2051)
sea_level_2000 = res_2000.intercept + res_2000.slope * years_2000_extended

plt.plot(years_2000_extended, sea_level_2000, color='green')

plt.xlabel('Year')
plt.ylabel('Sea Level (inches)')
plt.title('Rise in Sea Level')

plt.savefig('sea_level_plot.png')
plt.show()